# Generated by Django 4.1.7 on 2023-03-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
