# Generated by Django 4.1.7 on 2023-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginauth', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
