# Generated by Django 4.1.7 on 2023-04-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(max_length=254)),
                ('hire_date', models.DateTimeField()),
                ('birth_date', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('avtar', models.ImageField(null=True, upload_to='photos/users')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
