# Generated by Django 4.1.7 on 2023-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_company_type_company_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(),
        ),
    ]
