# Generated by Django 4.1.7 on 2023-04-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
