# Generated by Django 4.1.7 on 2023-04-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=10)),
                ('recipients', models.CharField(max_length=100)),
                ('hashtags', models.CharField(max_length=150, null=True)),
                ('comments', models.TextField(null=True)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='photos/user_form')),
            ],
        ),
    ]
